version: '3'

networks:
  my_network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_php_demo
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - my_network
  mysql:
    image: mysql:10.6.4
    container_name: mysql_php_demo
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: ${YOUR_DATABASE_NAME}
      MYSQL_USER: ${YOUR_USER_NAME}
      MYSQL_PASSWORD: ${YOUR_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${YOUR_PASSWORD}
      SERVICE_NAME: mysql
    networks:
      - my_network
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_demo
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9090:9000"
    networks:
      - my_network
